[build]
  functions = "netlify/functions"
[[redirects]]
  from = "/decision"
  to = "/decision/index.html"
  status = 200
[[redirects]]
  from = "/realdeal"
  to = "/realdeal/index.html"
  status = 200
[[redirects]]
  from = "/track"
  to = "/track/index.html"
  status = 200
[[redirects]]
  from = "/paycheck"
  to = "/paycheck/index.html"
  status = 200
[[redirects]]
  from = "/invest"
  to = "/invest/index.html"
  status = 200
[[redirects]]
  from = "/health"
  to = "/health/index.html"
  status = 200
[[redirects]]
  from = "/allocate"
  to = "/allocate/index.html"
  status = 200
[[redirects]]
  from = "/cost"
  to = "/cost/index.html"
  status = 200
[[redirects]]
  from = "/start"
  to = "/start/index.html"
  status = 200
